# .github/workflows/ci.yml
name: Next.js Git Flow CI/CD

on:
  push:
    branches:
      - main
      - develop
      - release/**
      - hotfix/**
      - feature/**
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test || echo "No tests yet"
      
      - name: Build Next.js app
        run: npm run build

  deploy-staging:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔧 Deploy to Staging (You can integrate Vercel/Firebase here)"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Deploy to Production"
